import Vue from 'vue'
import { Button,Input,Aside,Menu,Container ,Main,MenuItem,FormItem,Form,Loading,Link,Tabs} from 'element-ui'
import {TabPane,Divider,Row,Col,Dialog,Option,Select,DatePicker} from 'element-ui'
import {Drawer,Empty,Dropdown,DropdownMenu,DropdownItem,Upload,Tooltip} from 'element-ui'

Vue.use(Button)
Vue.use(Input)
Vue.use(Aside)
Vue.use(Menu)
Vue.use(Container)
Vue.use(Main)
Vue.use(MenuItem)
Vue.use(FormItem)
Vue.use(Form)
Vue.use(Loading)
Vue.use(Link)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Divider)
Vue.use(Row)
Vue.use(Col)
Vue.use(Dialog)
Vue.use(Option)
Vue.use(Select)
Vue.use(DatePicker)
Vue.use(Drawer)
Vue.use(Empty)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Upload)
Vue.use(Tooltip)